import Head from 'next/head'
import PurchaseForm from '../components/PurchaseForm'
import { useSelector, useDispatch } from 'react-redux'
import Navbar from '../components/Navbar'

export default function AddToCart( {carsData} ) {
  const selectedItem = useSelector( state => state.ui.selectedItem );

  if( selectedItem === undefined ) return <div>Loading...</div>

  return (
    <div>
      <Head>
        <title>Add to cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>
        <PurchaseForm /> 
      </main>

      <footer className="bg-black h-[10vh] mt-10">
            <div className="text-white font-light flex flex-row justify-evenly ">
              <p>About us</p>
              <p>Terms of use</p>
              <p>Privacy</p>
            </div>
      </footer>
    </div>
  )
}

