import Head from 'next/head'

import PurchaseForm from '../components/PurchaseForm'
import { useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { uiActions } from '../store/slices/uiSlice'
import Cart from '../components/Cart'
import Navbar from '../components/Navbar'

export default function EditCart( {carsData} ) {
  const currency = useSelector( state => state.ui.currency );
  const selectedItem = useSelector( state => state.ui.selectedItem );
  const modalIsOpen = useSelector( state => state.ui.modalIsOpen )
  const cartListIsOpen = useSelector( state => state.ui.cartListIsOpen )
  const dispatch = useDispatch();

  if( selectedItem === undefined ) return <div>Loading...</div>

  return (
    <div>
      <Head>
        <title>Edit cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>
        <PurchaseForm  editCart={true}/> 
      </main>

      <footer className="bg-black h-[10vh] mt-10">
            <div className="text-white font-light flex flex-row justify-evenly ">
              <p>About us</p>
              <p>Terms of use</p>
              <p>Privacy</p>
            </div>
      </footer>
    </div>
  )
}

