import Head from 'next/head'
import Card from '../components/Card'
import { useSelector, useDispatch } from 'react-redux'
import Navbar from '../components/Navbar'

export default function Home( {carsData} ) {

  if( carsData === undefined ) return <div>Loading...</div>

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>

        <div className='relative flex flex-col overflow-hidden items-center justify-center h-[50vh] bg-neutral-200 mb-10'>
          <h1 className="text-5xl z-20 text-center bg-white opacity-40 rounded-lg px-7 py-3 font-semibold">Buy a car!</h1>
          <video className="absolute z-10 object-cover h-full w-full" autoPlay loop muted>
            <source src='video.mp4' type="video/mp4"/>
          </video>
        </div>

        <div className='flex flex-row justify-center px-auto'>
          <div className='flex flex-col sm:flex-row flex-wrap justify-center sm:justify-center gap-10'>
            {carsData.map( car => {
              return(
                <Card key={Math.random()} carDetails={ car }/>
              )
            })}
          </div>
        </div>

      </main>


      <footer className="bg-black h-[10vh] mt-10">
            <div className="text-white font-light flex flex-row justify-evenly ">
              <p>About us</p>
              <p>Terms of use</p>
              <p>Privacy</p>
            </div>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  const req = await fetch(`https://xcaret-store-backend.herokuapp.com/api/`);
  const { data:carsData } = await req.json();
  console.log(carsData)
  return {
    props: {carsData},
  }

}