import Head from 'next/head'
import Card from '../components/Card'
import Navbar from '../components/Navbar'
import axios from 'axios'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { uiActions } from '../store/slices/uiSlice'
import {API} from '../utils/api'

export default function Home( {carsData} ) {
  const dispatch = useDispatch();
  const lang = useSelector( state => state.ui.language )
  const uiLang = useSelector( state => state.ui.uiLang )
  const ui = uiLang[lang]; 

  useEffect(() => {
    async function getLang() {
      // const res = await axios.get("http://localhost:3001/api/lang/");
      const res = await axios.get(`https://xcaret-store-backend-production.up.railway.app/api/lang/`);
      const langData = res.data.data;
      dispatch(uiActions.setUiLang(langData))
    }
    getLang()
    
    return () => {
      
    }
  }, [])

  if( carsData === undefined || ui === undefined) return <div>Loading...</div>

  return (
    <div>
      <Head>
        <title>Car Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>

        <div className='relative flex flex-col overflow-hidden items-center justify-center h-[50vh] bg-neutral-200 mb-10'>
          <h1 className="text-5xl z-20 text-center bg-white opacity-40 rounded-lg px-7 py-3 font-semibold">{ui.header}</h1>
          <video className="absolute z-10 object-cover h-full w-full" autoPlay loop muted>
            <source src='video.mp4' type="video/mp4"/>
          </video>
        </div>

        <div className='flex flex-row justify-center px-auto'>
          <div className='flex flex-col sm:flex-row flex-wrap justify-center sm:justify-center gap-10'>
            {carsData.map( car => {
              return(
                <Card key={car._id} carDetails={ car }/>
              )
            })}
          </div>
        </div>

      </main>


      <footer className="bg-black h-[10vh] mt-10">
            <div className="text-white font-light flex flex-row justify-evenly ">
              <p>About us</p>
              <p>Terms of use</p>
              <p>Privacy</p>
            </div>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  console.log(API)
    let res = await fetch(`https://xcaret-store-backend-production.up.railway.app/api/`);
    const { data:carsData } = await res.json();

  return {
    props: {carsData},
  }

}